import type { Config } from "tailwindcss";

import { heroui } from "@heroui/react";

const config = {
    darkMode: ["class"],
    content: [
        "./pages/**/*.{ts,tsx}",
        "./components/**/*.{ts,tsx}",
        "./app/**/*.{ts,tsx}",
        "./src/**/*.{ts,tsx}",
        "./node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}",
    ],
    prefix: "",
    theme: {
        extend: {},
    },
    plugins: [
        heroui({
            layout: {
                fontSize: {
                    tiny: "0.5rem",
                    small: "0.875rem",
                    medium: "1rem",
                    large: "2rem",
                },
                radius: {
                    small: "0.25rem",
                    medium: "0.5rem",
                    large: "0.75rem",
                },
            },
            themes: {
                dark: {
                    colors: {
                        background: "#08070D",
                        foreground: "#FFFFFF",
                        primary: {
                            DEFAULT: "#723AFF",
                            "100": "#E7D7FF",
                            "200": "#CDB0FF",
                            "300": "#B188FF",
                            "400": "#996BFF",
                            "500": "#723AFF",
                            "600": "#572ADB",
                            "700": "#401DB7",
                            "800": "#2B1293",
                            "900": "#1D0B7A",
                        },
                        secondary: {
                            DEFAULT: "#11CDFC",
                            "100": "#CFFEFA",
                            "200": "#9FFEFC",
                            "300": "#6FF6FE",
                            "400": "#4CE6FD",
                            "500": "#11CDFC",
                            "600": "#0CA0D8",
                            "700": "#0879B5",
                            "800": "#055692",
                            "900": "#033E78",
                        },
                        success: {
                            DEFAULT: "#54BF2D",
                            "100": "#EAFBD5",
                            "200": "#D0F8AC",
                            "300": "#ABEB7F",
                            "400": "#86D85C",
                            "500": "#54BF2D",
                            "600": "#3AA420",
                            "700": "#258916",
                            "800": "#146E0E",
                            "900": "#085B09",
                        },
                        warning: {
                            DEFAULT: "#FFDE0C",
                            "100": "#FFFBCE",
                            "200": "#FFF59D",
                            "300": "#FFEF6D",
                            "400": "#FFE848",
                            "500": "#FFDE0C",
                            "600": "#DBBB08",
                            "700": "#B79A06",
                            "800": "#937A03",
                            "900": "#7A6302",
                        },
                        danger: {
                            DEFAULT: "#FF4747",
                            "100": "#FFE6DA",
                            "200": "#FFC8B5",
                            "300": "#FFA390",
                            "400": "#FF8075",
                            "500": "#FF4747",
                            "600": "#DB3342",
                            "700": "#B7233D",
                            "800": "#931637",
                            "900": "#7A0D33",
                        },
                    },
                },
                light: {
                    colors: {
                        background: "#FFFFFF",
                        foreground: "#08070D",
                        primary: {
                            DEFAULT: "#723AFF",
                            "100": "#E7D7FF",
                            "200": "#CDB0FF",
                            "300": "#B188FF",
                            "400": "#996BFF",
                            "500": "#723AFF",
                            "600": "#572ADB",
                            "700": "#401DB7",
                            "800": "#2B1293",
                            "900": "#1D0B7A",
                        },
                        secondary: {
                            DEFAULT: "#11CDFC",
                            "100": "#CFFEFA",
                            "200": "#9FFEFC",
                            "300": "#6FF6FE",
                            "400": "#4CE6FD",
                            "500": "#11CDFC",
                            "600": "#0CA0D8",
                            "700": "#0879B5",
                            "800": "#055692",
                            "900": "#033E78",
                        },
                        success: {
                            DEFAULT: "#54BF2D",
                            "100": "#EAFBD5",
                            "200": "#D0F8AC",
                            "300": "#ABEB7F",
                            "400": "#86D85C",
                            "500": "#54BF2D",
                            "600": "#3AA420",
                            "700": "#258916",
                            "800": "#146E0E",
                            "900": "#085B09",
                        },
                        warning: {
                            DEFAULT: "#FFDE0C",
                            "100": "#FFFBCE",
                            "200": "#FFF59D",
                            "300": "#FFEF6D",
                            "400": "#FFE848",
                            "500": "#FFDE0C",
                            "600": "#DBBB08",
                            "700": "#B79A06",
                            "800": "#937A03",
                            "900": "#7A6302",
                        },
                        danger: {
                            DEFAULT: "#FF4747",
                            "100": "#FFE6DA",
                            "200": "#FFC8B5",
                            "300": "#FFA390",
                            "400": "#FF8075",
                            "500": "#FF4747",
                            "600": "#DB3342",
                            "700": "#B7233D",
                            "800": "#931637",
                            "900": "#7A0D33",
                        },
                    },
                },
            },
        }),
    ],
} satisfies Config;

export default config;
